import express from "express";
import cookieParser from "cookie-parser";
import "dotenv/config";
import mongoose from "mongoose";
import connectionDb from "./utils/dbconfig";
import Authrouter from "./routes/auth";
import userrouter from "./routes/user";
import productrouter from "./routes/product";
import wishlistrouter from "./routes/wishlist";
import cartrouter from "./routes/cart";
import {verifyToken} from "./middleware/verifytoken";
import  test  from "./routes/test";
import  address  from "./routes/address";
import  order  from "./routes/order";
import path from "path";
const app  = express();
app.use(express.json());
app.use(cookieParser());
app.use("/image", express.static(path.join(__dirname, "image")));
app.use("/api/auth",  Authrouter);
app.use("/api/user" ,userrouter);
app.use("/api/product" ,productrouter);
app.use("/api/product" ,productrouter);
app.use("/api/wishlist" ,wishlistrouter); 
app.use("/api/cart" ,cartrouter); 
app.use("/api/adress" ,cartrouter); 
app.use("/api/test" ,test); 
app.use("/api/address" ,address); 
app.use("/api/order" ,order); 
app.listen(process.env.PORT, () => {
    connectionDb();
    console.log(`Server is running on port ${process.env.PORT}`);
});